account_id = '4afac2ff1d8101bb0852545f1e7783fe'
name = 'tinydb'
main = 'src/index.ts'
workers_dev = false
compatibility_date = '2024-10-01'
compatibility_flags = [ 'nodejs_compat' ]

routes = [ 'tinydb.danifoldi.com/*' ]
kv_namespaces = [
  { binding = 'KV', id = 'b068aa09d3d3457eb3e7d881ed7b9418' }
]

[observability]
enabled = true
